---
home:
  children:
    proxmox_hosts:
      hosts:
        pve:
          ansible_host: 192.168.0.59
          ansible_user: root
    lxcs:
      hosts:
        jellyfin:
          ansible_host: 192.168.0.99
          ansible_user: root
          vmid: 101
          proxmox_host: pve
          lxc_features:
            - tun
            - nas_idmap
