baseURL = "https://monotrope.au"
languageCode = "en-au"
title = "Monotrope"

[markup.goldmark.extensions.typographer]
  disable = false

[markup.goldmark.renderer]
  unsafe = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[params]
  description = "writing on technology, books, and ideas."
