services:
  obsidian-sync:
    build: .
    container_name: obsidian-sync
    restart: unless-stopped
    networks:
      - monotrope
    volumes:
      - obsidian_config:/config
      - obsidian_vault:/vault
    env_file:
      - .env

networks:
  monotrope:
    external: true

volumes:
  obsidian_config:
  obsidian_vault:
