---
calibre_web_dir: /opt/calibre
calibre_web_puid: 1028
calibre_web_pgid: 1028
calibre_web_tz: Australia/Sydney
calibre_web_port: 8083
calibre_web_library_path: /library/books
calibre_web_image: crocodilestick/calibre-web-automated:latest
