services:
  calibre-web:
    image: git.monotrope.au/louis/calibre-web:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8083:8083"
    volumes:
      - calibre_config:/config
      - kobodl_config:/home/config
      - library:/calibre-library
      - downloads:/downloads
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: "Australia/Sydney"
    networks:
      - default
      - monotrope

networks:
  default:
  monotrope:
    external: true

volumes:
  calibre_config:
  kobodl_config:
  library:
  downloads:
